version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.codehaus.groovy:groovy-xml
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-testng
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-test
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-templates
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-swing
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-sql
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-servlet
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-nio
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-jsr223
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-json
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-jmx
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-groovysh
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-groovydoc
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-docgenerator
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-console
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-bsf
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-ant
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy-all
    versions:
    - 2.4.21
  - dependency-name: org.codehaus.groovy:groovy
    versions:
    - 2.4.21
  - dependency-name: org.eclipse.jetty.websocket:websocket-server
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty.websocket:websocket-client
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty.websocket:javax-websocket-server-impl
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-xml
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-servlets
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-security
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-jmx
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:apache-jsp
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:apache-jstl
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-io
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-http
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-deploy
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-continuation
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-client
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.springframework:spring-framework-bom
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.seleniumhq.selenium:htmlunit-driver
    versions:
    - 2.46.0
    - 2.47.1
    - 2.48.0
  - dependency-name: net.sourceforge.htmlunit:htmlunit
    versions:
    - 2.46.0
    - 2.47.1
    - 2.48.0
  - dependency-name: io.undertow:undertow-websockets-jsr
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: io.undertow:undertow-servlet
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: io.undertow:undertow-core
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: com.fasterxml.jackson.module:jackson-module-parameter-names
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-kotlin
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-jaxb-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-json-org
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-joda
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jaxrs
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-hibernate5
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-hibernate4
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-guava
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-xml
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-smile
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-csv
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-cbor
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.springframework.amqp:spring-rabbit
    versions:
    - 2.3.4
    - 2.3.5
  - dependency-name: org.springframework.amqp:spring-amqp
    versions:
    - 2.3.4
    - 2.3.5
  - dependency-name: org.apache.ant:ant-launcher
    versions:
    - 1.10.9
  - dependency-name: org.apache.ant:ant
    versions:
    - 1.10.9
  - dependency-name: org.apache.activemq:activemq-web
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-stomp
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-spring
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-shiro
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-runtime-config
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-run
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-ra
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-pool
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-partition
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-osgi
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-openwire-legacy
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-openwire-generator
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-mqtt
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-log4j-appender
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-leveldb-store
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-karaf
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-kahadb-store
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-jms-pool
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-jdbc-store
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-jaas
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-http
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-console
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-client
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-camel
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-broker
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-blueprint
    versions:
    - 5.16.1
  - dependency-name: org.apache.activemq:activemq-amqp
    versions:
    - 5.16.1
  - dependency-name: org.springframework.batch:spring-batch-test
    versions:
    - 4.3.1
  - dependency-name: org.springframework.batch:spring-batch-integration
    versions:
    - 4.3.1
  - dependency-name: org.springframework.batch:spring-batch-infrastructure
    versions:
    - 4.3.1
  - dependency-name: org.springframework.batch:spring-batch-core
    versions:
    - 4.3.1
  - dependency-name: org.springframework.security.oauth:spring-security-oauth2
    versions:
    - 2.5.0.RELEASE
  - dependency-name: org.springframework.security.oauth:spring-security-oauth
    versions:
    - 2.5.0.RELEASE
  - dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
